#!/bin/bash

ROOT="$(git rev-parse --show-toplevel)"

for f in $ROOT/test/testcases/*.tig; do
    fn="${f%.*}"
    printf "\n\n$(basename $fn)"
    if ! command -v colordiff &> /dev/null
    then
        diff "$fn.tig" "$fn.parse"
    else
        colordiff "$fn.tig" "$fn.parse"
    fi
done
