version: 2.1

jobs:
  test:
    docker:
      - image: ayazhafiz/tigercompiler
    steps:
      - checkout
      - run: eval $(opam env) && ./tool unittest
      - run: eval $(opam env) && ./tool uitest

workflows:
  test:
    jobs:
      - test
