version: 2.1

jobs:
  test:
    docker:
       - image: ocaml/opam2
    steps:
      - checkout
      - run: opam install -y dune menhir
      - run: ./tool unittest
      - run: ./tool uitest

workflows:
  test:
    jobs:
      - test
